In [4]:
import sympy
import numpy

In [5]:
vxp = numpy.array([1,0])

In [3]:
[[1,0],[0,-1]]

[[-1, 0], [0, -1]]

In [6]:
print vxp

[1 0]


In [7]:
ident = numpy.array(
    [[1,0],
     [0,1]])

In [8]:
ident.dot(vxp)

array([1, 0])

In [9]:
trn1 = numpy.array(
    [[0,1],
     [1,0]])

In [10]:
trn1.dot(vxp)

array([0, 1])

In [11]:
trn2 = numpy.array([[0,-1],[-1,0]])

In [12]:
trn2.dot(vxp)

array([ 0, -1])

In [1]:
"""
Actions: 
since a real path is real everywhere along it, realness is a locally discernable property? 
meaning we can assess realness by integrating the realness of each point along a path we can get the collective realness for said path.
call that collective realness the action, the way the path evolves will generate an extremum of action
"""

'\nActions: \nsince a real path is real everywhere along it, realness is a locally discernable property? \nmeaning we can assess realness by integrating the realness of each point along a path we can get the collective realness for said path.\ncall that collective realness the action, the way the path evolves will generate an extremum of action\n'

In [ ]:
"""Optics
properties:
speed of light in vacuum V0=c
speed of light in medium Vn = c/n
reflection rule: light will bounce off surfaces symmetrically with respect to the normal of the surface.
refraction rule: the ratio of the sin of the angles with respect to the normal of the medium boundary will equal the inverse ratio of indices of refraction.
reflection rule comes out from the 2 fastest paths 2 points when a mirror is available are 3
"""